# Array


In [1]:
import array as arr

In [2]:
a=arr.array('i',[1,2,3])         #creating an array a
a

array('i', [1, 2, 3])

In [3]:
b=arr.array('i',[4,5,6])          #creating an array b
b

array('i', [4, 5, 6])

In [4]:
a[1:]                            #slicing

array('i', [2, 3])

In [6]:
a[2:]

array('i', [3])

In [8]:
b[1:]

array('i', [5, 6])

In [11]:
a[::-1]               #reverse

array('i', [3, 2, 1])

In [23]:
b.append(7)                    #append
b

array('i', [4, 5, 6, 7])

In [24]:
b.remove(5)               #remove
b

array('i', [4, 6, 7])

In [25]:
for i in b:
    print(i)

4
6
7


In [27]:
for i in a:
    print(i,end=",")

1,2,3,4,4,4,4,

In [28]:
a+b

array('i', [1, 2, 3, 4, 4, 4, 4, 4, 6, 7])

# Numpy

In [30]:
import numpy as np

In [33]:
k=np.array([(1,2,3),(2,1,4)])
n=np.array([(2,1,4),(3,7,9)])
k


array([[1, 2, 3],
       [2, 1, 4]])

In [34]:
n

array([[2, 1, 4],
       [3, 7, 9]])

In [35]:
k.ndim          #to check the dimensions

2

In [36]:
n.itemsize

4

In [37]:
k.dtype

dtype('int32')

In [39]:
n.shape

(2, 3)

In [41]:
k.reshape(3,2)

array([[1, 2],
       [3, 2],
       [1, 4]])

In [42]:
n.min()

1

In [43]:
k.max()

4

In [44]:
k.sum()

13

In [45]:
n.sum()

26

In [46]:
g=np.linspace(1,5,8)
g

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [47]:
k.sum(axis=0)     #column

array([3, 3, 7])

In [48]:
n.sum(axis=0)

array([ 5,  8, 13])

In [49]:
n.sum(axis=1)

array([ 7, 19])

In [50]:
np.sqrt(n)

array([[1.41421356, 1.        , 2.        ],
       [1.73205081, 2.64575131, 3.        ]])

In [51]:
np.std(k)

1.0671873729054748

In [52]:
np.mean(k)

2.1666666666666665

In [53]:
k

array([[1, 2, 3],
       [2, 1, 4]])

In [55]:
k[0,1]

2

In [56]:
k[0:2,1]

array([2, 1])

In [58]:
k[k!=2]

array([1, 3, 1, 4])

In [59]:
k[k>1]

array([2, 3, 2, 4])

In [60]:
k.sort()
k

array([[1, 2, 3],
       [1, 2, 4]])